strength.uuid = '78d16016-b2c3-48c0-8334-4dff96a1b42d'
strength.name = 'test'
strength.amount = 1337.0
strength.operation = 'ADD_NUMBER'
strength.equipmentSlot = 'HAND'
skyIslandOrigin.xCoord = 1.549687
skyIslandOrigin.yCoord = 58.52578
skyIslandOrigin.zCoord = 8421257.577845
boundingBox.corner1.xCoord = 10.0
boundingBox.corner1.yCoord = 20.0
boundingBox.corner1.zCoord = 10.0
boundingBox.corner2.xCoord = 60.0
boundingBox.corner2.yCoord = 40.0
boundingBox.corner2.zCoord = 300.0
color.red = 255
color.green = 60
color.blue = 0
color.alpha = 255
fireworkEffect.type = 'BURST'
fireworkEffect.colors = [{red = 255, green = 0, blue = 0, alpha = 255}]
fireworkEffect.fadeColors = [{red = 0, green = 255, blue = 255, alpha = 255}]
fireworkEffect.flicker = false
fireworkEffect.trail = false
location.uid = '00000000-0000-0000-0000-000000000000'
location.name = 'world'
location.xCoord = 0.0
location.yCoord = 0.0
location.zCoord = 0.0
location.yaw = 0.0
location.pitch = 0.0
namespacedKey.namespace = 'key'
namespacedKey.key = 'name'
pattern.color = 'RED'
pattern.pattern = 'BASE'
potionEffect.amplifier = 1
potionEffect.duration = 1
potionEffect.type.namespace = 'minecraft'
potionEffect.type.key = 'blindness'
potionEffect.ambient = true
potionEffect.particles = true
potionEffect.icon = true
heavyWeightedPressurePlateJump.xCoord = 1.549687
heavyWeightedPressurePlateJump.yCoord = 58.52578
heavyWeightedPressurePlateJump.zCoord = 8421257.577845
