name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev*
      - feature/*
      - fix/*

jobs:
  publish-central:
    environment: build
    runs-on: ubuntu-latest
    name: Publish to Maven Central

    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
      - name: Build with Gradle
        run: ./gradlew --build-cache build
      - name: Test with Gradle
        run: ./gradlew test
      - name: Publish to Maven Central
        run: ./gradlew publish -PforceSign=true
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: "${{ secrets.SONATYPE_USERNAME }}"
          ORG_GRADLE_PROJECT_sonatypePassword: "${{ secrets.SONATYPE_PASSWORD }}"
          ORG_GRADLE_PROJECT_rainbowdashlabsSigningKey: "${{ secrets.RAINBOWDASHLABS_SIGN_KEY }}"
          ORG_GRADLE_PROJECT_rainbowdashlabsSigningPassword: "${{ secrets.RAINBOWDASHLABS_GPG_PASSWORD }}"
