name: Verify state

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          architecture: x64
      - name: Build with Gradle
        run: ./gradlew --build-cache build  -x test
      - name: Test with Gradle
        run: ./gradlew test
